name: Quality Check, build and deploy

on: [push, pull_request]

jobs:
  sonar_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - run: npm install

      - run: npm test

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: SonarQube Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@master
        # Force to fail step after specific time
        timeout-minutes: 5
        env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build_job:
    needs: sonar_job

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - run: npm install

      - name: React build
        run: npm run build

      - uses: actions/upload-artifact@v4
        if: startsWith(github.event.ref, 'refs/tags/')
        with:
          name: react
          path: dist 


  itch_publish_job:
    needs: build_job

    env:
      BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}

    runs-on: ubuntu-latest

    if: startsWith(github.event.ref, 'refs/tags/')

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/download-artifact@v4
        with:
          name: react
          path: dist/

      - name: Install butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip

          chmod +x butler

          ./butler -V

      - name: Upload build
        run: |
          ./butler push dist/ elanis/neverending:web-beta
